[package]
name = "scafra-test-service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
scafra = {
    git = "https://github.com/Scafra/Scafra",
    rev = "c7f9dd227eb98e02b0882d6264259911956dd7f5",
}
scafra-bootui = {
    git = "https://github.com/Scafra/Scafra",
    rev = "c7f9dd227eb98e02b0882d6264259911956dd7f5",
}
serde = { version = "1", features = ["derive"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
